server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    register-with-eureka: false

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
logging:
  level:
    com.chenfx.springcloud.service.PaymentFeignService: debug